### ISSUE TITLE
MANIFEST.in may not be needed with setuptools_scm

### ISSUE THREAD

**Issue by niksirbi** [neuroinformatics-unit/python-cookiecutter#32]
I have stumbled upon some information that `MANIFEST.in` is no longer needed when using `setuptools_scm`. This is because `setuptools_scm`, by default includes all version-controlled files in the sdist. 
To learn more about this see the following:
* [Helpful blogpost](https://www.remarkablyrestrained.com/python-setuptools-manifest-in/)
* [Stack overflow thread](https://stackoverflow.com/questions/24727709/do-python-projects-need-a-manifest-in-and-what-should-be-in-it)
* [GitHub issue](https://github.com/pypa/setuptools_scm/issues/190)

Thought @adamltyson ? Getting rid of `MANIFEST.in` would mean that all git-tracked files (and only those) are included in the sdist. Is that a sensible thing to do? 

If we don't get rid of it, I am not sure we still get the behaviour we want, due to how this interacts with `setuptools_scm` (see the linked issue)

**Comment by adamltyson** [comment]
I think we need to look into this, because there's lots of stuff that's in the repo that's shouldn't be in the sdist (test data in particular). 
I read the blog that states everything in the repo should be in sdist, but I don't agree. The sdist isn't used for development, it's used for installation when there's no wheel available.

I think we'll always need to tool to determine what gets packaged and what doesn't.
